vim.opt.whichwrap = "b,s,h,l,<,>"
vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.fillchars = "eob: "
vim.opt.cmdheight = 0
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.numberwidth = 4
vim.opt.hlsearch = false
vim.opt.termguicolors = true
vim.opt.cursorline = true
vim.opt.colorcolumn = "80"
vim.opt.hidden = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.showtabline = 0
vim.opt.title = true
vim.opt.mouse = "a"
vim.opt.shortmess:append("stcC")
vim.opt.undofile = true
vim.opt.completeopt = {"menuone", "noinsert"}
vim.opt.pumheight = 10
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smarttab = true
vim.opt.smartindent = true
vim.opt.backup = false
vim.opt.updatetime = 200
vim.opt.signcolumn = "yes"
